#!/usr/bin/env bash

## Copyright (C) 2020-2024 spaciousejar

# i3 directory
DIR="$HOME/.config/i3"

# Launch dunst daemon
if [[ `pidof dunst` ]]; then
	pkill dunst
fi

dunst -config "$DIR"/dunstrc &
